# Generated by Django 3.2.9 on 2022-01-21 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0024_auto_20220104_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата')),
                ('telegram', models.IntegerField(default=0, verbose_name='Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='TGProfileStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.BooleanField(default=True)),
                ('last_activity', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='data.tguser')),
            ],
        ),
    ]
