# Generated by Django 3.2.9 on 2021-11-24 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='value',
        ),
        migrations.AddField(
            model_name='bet',
            name='money',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='bet',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='parimatch_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='sports_ru_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='team',
            name='first',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='balance',
            field=models.BigIntegerField(default=1000),
        ),
    ]
