# Generated by Django 3.2.9 on 2021-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'verbose_name_plural': 'Ставки'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории видов спорта'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Стороны'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name_plural': 'Пользователи Telegram'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name_plural': 'Турниры'},
        ),
        migrations.AddField(
            model_name='tguser',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
