# Generated by Django 3.2.9 on 2021-11-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20211124_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
