# Generated by Django 3.2.9 on 2021-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20211125_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bet',
            field=models.FloatField(default=1.0),
        ),
    ]
