# Generated by Django 3.2.9 on 2021-11-26 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_team_bet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='not_supported',
            field=models.BooleanField(default=False, verbose_name='Не поддерживается'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна ли ставка'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='money',
            field=models.IntegerField(default=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Оплачена ли ставка'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='data.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='data.tguser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='value',
            field=models.FloatField(default=1.0, verbose_name='Коэффициент'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='winner',
            field=models.BooleanField(default=False, verbose_name='Выиграл ли'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Статус окончания события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(default='', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parimatch_link',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на PariMatch'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sports_ru_link',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на Sports'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Время начала игры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='data.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.TextField(default='', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='team',
            name='bet',
            field=models.FloatField(default=1.0, verbose_name='Ставка в данный момент'),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='data.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='team',
            name='first',
            field=models.BooleanField(default=True, verbose_name='Хозяин ли площадки?'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(default='', verbose_name='Имя команды'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='balance',
            field=models.BigIntegerField(default=1000, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='language',
            field=models.CharField(default='en', max_length=2, verbose_name='Языковой пакет'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя Telegram'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус активности аккаунта'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_language',
            field=models.CharField(default='en', max_length=2, verbose_name='Языковой пакет в Telegram'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.TextField(default='', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='data.subcategory', verbose_name='Подкатегория'),
        ),
    ]
