# Generated by Django 3.2.9 on 2021-11-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20211126_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='on_moderation',
            field=models.BooleanField(default=False, verbose_name='На модерации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ended',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус окончания события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='not_supported',
            field=models.BooleanField(blank=True, default=False, verbose_name='Не поддерживается'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parimatch_link',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на PariMatch'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sports_ru_link',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на Sports'),
        ),
        migrations.CreateModel(
            name='EventOnModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ink', models.CharField(default='', max_length=100)),
                ('message_id', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='data.event')),
            ],
        ),
    ]
