# Generated by Django 3.2.9 on 2021-11-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20211126_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventonmoderation',
            old_name='ink',
            new_name='link',
        ),
    ]
