# Generated by Django 3.2.9 on 2021-11-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_ink_eventonmoderation_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Имя команды')),
                ('first', models.BooleanField(default=True, verbose_name='Хозяин ли площадки?')),
            ],
            options={
                'verbose_name_plural': 'Стороны',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='on_moderation',
        ),
        migrations.DeleteModel(
            name='EventOnModeration',
        ),
        migrations.AddField(
            model_name='teamevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='data.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='data.teamevent', verbose_name='Команда'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
