# Generated by Django 3.2.9 on 2021-11-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20211126_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parimatch_name', models.CharField(default='', max_length=40)),
                ('sports_name', models.CharField(default='', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.RemoveField(
            model_name='teamevent',
            name='name',
        ),
        migrations.AddField(
            model_name='teamevent',
            name='bet',
            field=models.FloatField(default=1.0, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='teamevent',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data.team', verbose_name='Команда'),
            preserve_default=False,
        ),
    ]
