# Generated by Django 3.2.9 on 2021-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20211126_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sports_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
