# Generated by Django 3.2.9 on 2021-11-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_team_sports_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='parimatch_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sports_name',
        ),
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтвержденный')),
                ('primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='data.team', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='TeamModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(default=0, verbose_name='ID сообщения')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='data.teamname', verbose_name='Имя на заявку')),
            ],
        ),
    ]
