# Generated by Django 3.2.9 on 2021-11-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20211129_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammoderation',
            options={'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='teamname',
            options={'verbose_name_plural': 'Названия команд'},
        ),
        migrations.AddField(
            model_name='teamname',
            name='denied',
            field=models.BooleanField(default=False, verbose_name='Отказанный'),
        ),
    ]
