# Generated by Django 3.2.9 on 2021-11-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20211201_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='not_supported',
        ),
    ]
