# Generated by Django 3.2.9 on 2021-12-01 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_event_not_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
