# Generated by Django 3.2.9 on 2021-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_bet_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя Telegram'),
        ),
    ]
