# Generated by Django 3.2.9 on 2021-12-01 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_tguser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='data.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Пользовательские настройки',
            },
        ),
    ]
