# Generated by Django 3.2.9 on 2021-12-31 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_tguser_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expresses', to='data.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Экспресс',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='express',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='data.express', verbose_name='Экспресс'),
        ),
    ]
